- name: Clone the Kubernetes manifests repository
  git:
    repo: https://github.com/ritik-rkg/Talent_Bridge_K8s.git
    dest: /tmp/Talent_Bridge_K8s
  register: repo_status

- name: Show repository clone status
  debug:
    msg: "Repository cloning was successful: {{ repo_status }}"
